### ISSUE TITLE
submitOnEnter not working

### ISSUE THREAD

**Issue by konrad-ch** [marmelab/react-admin#1797]
```submitOnEnter={false}``` does not work, form submits anyway.

**What you were expecting:**
Form not to submit.

**What happened instead:**
Form submits - acts like html form with ```method="get"``` - copies form parameter to url query for some reason.

**Steps to reproduce:**
create very standard component as in related code below

**Related code:**
```
export const UserEdit = (props) => (
    <Edit {...props}>
        <SimpleForm submitOnEnter={false}>
            <TextInput source="userName"/>
        </SimpleForm>
    </Edit>
);
```

**Other information:**

**Environment**

* React-admin version: v2.0.0-RC2
* Last version that did not exhibit the issue (if applicable): didn't checked
* React version: 16.3.2
* Browser: Chrome 66
* Stack trace (in case of a JS error): none

**Comment by djhi** [comment]
I managed to reproduce it for some forms but not all. See https://codesandbox.io/s/73l4oqv1l6

`PostCreate` which uses `SimpleForm` shows the problem. You can submit with enter when `submitOnEnter` is `false`.

`PostEdit` which uses `TabbedForm` does not show the problem.

`CommentCreate` which uses `SimpleForm` does not show the problem.

`CommentEdit` which uses `SimpleForm` does not show the problem.

**Comment by fzaninotto** [comment]
@djhi does #2032 fix that?

**Comment by fzaninotto** [comment]
Fixed by #2064

**Comment by RichardSieg** [comment]
It is not fixed by #2064, since the PR is not merged. I have the same issue in my SimpleForm and used the `action="javascript: void(0)"` hack to avoid this behavior. Please reopen the issue.

**Comment by twd38** [comment]
Did this ever get fixed? I'm still experiencing this issue on SimpleForm even when including `submitOnEnter={false} `

**Comment by adrien-may** [comment]
PR #2064 is now closed but I feel the problem is still present. Is any work planned on this ?

**Comment by fzaninotto** [comment]
No, because this issue is closed. Please open a new issue by following the issue template.
