### ISSUE TITLE
AutocompleteInput pop-up after choice is selected

### ISSUE THREAD

**Issue by Ken-Lim** [marmelab/react-admin#2428]
**What you were expecting:**
After choice is selected, AutocompleteInput filled the textInput with selected choice

**What happened instead:**
After choice is selected, AutocompleteInput filled the textInput with selected choice then pop-up all the choices again

**Steps to reproduce:**
1. Goto demo site, to edit an order (e.g. https://marmelab.com/react-admin-demo/#/commands/280)
2. Enter a customer name in the Customer field
3. Select the choice with your mouse
4. All choices were pop-up again

Please see the attached GIF for the issue
![autocomplete](https://user-images.githubusercontent.com/26237537/46902325-230aff00-cef6-11e8-8c14-0c733d5ad249.gif)

**Comment by fzaninotto** [comment]
Confirmed. Weird bug.

**Comment by Ken-Lim** [comment]
> Hello @Ken-Lim and @fzaninotto,
> I'm still experiencing this issue with an Autocomplete inside a Reference Input, with react-admin 2.4.0 and react-autosuggest ^9.4.2 in package-lock.json.
> 
> Little note : The ReferenceInput is outside a Create/Edit page so using a SimpleForm and overriding the form prop
> 
> ```
>  render() {
>     const { deviceId } = this.state;
> 
>     return (
>         <SimpleForm form="replace-device-form" resource="Device" save={this.handleSubmit}>
>             <ReferenceInput
>                 label="Test issue 2428"
>                 source="deviceId"
>                 reference="Device"    
>                 onChange={(event, deviceId) => console.log(`New deviceId ${deviceId}`)}
>             >
>                 <AutocompleteInput optionText="identification" />
>             </ReferenceInput>
>         </SimpleForm>
>     )
> }
> ```
> 
> Any idea ? Upgrading to 9.4.2 has fixed the issue for you ?

I upgraded to react-admin 2.4.0, which uses the react-autosuggest 9.4.2.
Unfortunately, the issue is not resolve for me.

**Comment by FACOLOMBANI** [comment]
i fixed this issue by adding focusInputOnSuggestionClick={false} props to the AutoSuggest component.

**Comment by fzaninotto** [comment]
reopening as the issue seems not fixed

**Comment by Oupsla** [comment]
Forwarding message for example of the issue

> Here : https://codesandbox.io/s/lrro0q4wnm
> 
> Go to the custom page, then write something (like omnis) in the autocomplete input and then select something (and the selection container will open again)

**Comment by petmongrels** [comment]
This issue is not fixed.
I can see my dependency to be "react-autosuggest": "^9.4.2", but the issue persists.

**Steps to reproduce:**
Please find the GIF that explains the issue here: http://g.recordit.co/ng8QhldeJB.gif

**Related code:**
My code is like the following:
```
<ReferenceInput label="Districts" source="districtId" reference="district" validate={[required("Mandatory")]} perPage={20}>
        <AutocompleteInput source="district" optionText="name"/>}
</ReferenceInput>
```

**Other information:**

**Environment**
* React-admin version: "react": "^16.6.3",
    "react-admin": "^2.5.1",
    "react-dom": "^16.6.3"
* Browser: Chrome
* Stack trace (in case of a JS error): No Error On Console.

**Comment by zohaib-zix** [comment]
> i fixed this issue by adding focusInputOnSuggestionClick={false} props to the AutoSuggest component.

how ?

**Comment by hoangtuan438** [comment]
@fzaninotto  
I see it too on demo site https://marmelab.com/react-admin-demo/#/commands/312
the issue isn't fixed. The popup suggestion is still show again after clicking. Here's my video: https://drive.google.com/file/d/1TGRL5r0R-2-18VoYuErq_7QVsB-nbjRx/view

**Comment by hoangtuan438** [comment]
@fzaninotto @Kmaschta 

Is there anything new on the ticket? the issue was resolved?

Thanks

**Comment by Kmaschta** [comment]
Reopening this issue since it's not fixed as of the 2.8.2, we can reproduce the issue on the demo:
https://marmelab.com/react-admin-demo/#/commands

![Posters Galore Administration](https://user-images.githubusercontent.com/1819833/54771371-67b56780-4c05-11e9-9b5b-d1f982469a3a.gif)

There is also a [few reports](https://github.com/marmelab/react-admin/pull/2992#issuecomment-474205644)

**Comment by FACOLOMBANI** [comment]
I forked the complete component because i needed lots of customisations in it, i solve this problem by adding focusInputOnSuggestionClick={false} prop to the Autosuggest component.

**Comment by Kmaschta** [comment]
PR are welcome :)

**Comment by FACOLOMBANI** [comment]
Since version 2.5.0 you can pass props directly from the AutocompleteInput to the Autosuggest : 'Add ability to pass custom props to react-autosuggest from <AutocompleteInput>> (#2410) (AskseL)' 
So if you do the following it should work.
`<AutocompleteInput` source="district" optionText="name" focusInputOnSuggestionClick={false}/>`

**Comment by fzan** [comment]
Hello,
this issue is still open? I have the same behaviour, the AutocompleteInput reopens after selection.
:(

**Comment by Kmaschta** [comment]
Yep, it's still open.

Related to #3031

**Comment by amayatsky** [comment]
If I set `focusInputOnSuggestionClick={false}` on the ReferenceInput or AutocompleteInput selection just stops working.
I've made a sort of a fix for that with normalize but I don't know if this is good by any means.
```
normalize={
(value, prevValue) => {
  if (value !== prevValue && previousGoodValue === undefined) {
    previousGoodValue = value;
    return value;
  }
  if (value !== prevValue && prevValue === previousGoodValue) {
    previousGoodValue = value;
    return value;
  }
  return previousGoodValue;
};
}
```

**Comment by fzaninotto** [comment]
Fixed by #3031
