### ISSUE TITLE
Custom Logout Button from documentation doesn't work as intended

### ISSUE THREAD

**Issue by vaiulian** [marmelab/react-admin#3033]
**What you were expecting:**
Logout the user when clicking LOGOUT on a custom Logout Button component.

**What happened instead:**
Nothing happens.
Action is not DISPATCHED.
DropDown Menu item is positioned wrong.

![React Admin 3-21-2019 1-26-36 PM](https://user-images.githubusercontent.com/12198262/54749378-037ead80-4bdd-11e9-8647-6ccfd1ead0ed.png)

**Steps to reproduce:**
I've added the `MyLogoutButton.js` component and added `logoutButton={MyLogoutButton}` to Admin. 

Like in documentation: https://marmelab.com/react-admin/Authentication.html#adding-a-logout-button

**Related code:**
https://codesandbox.io/s/k9714xnr5v

**Other information:**
I'm trying to redirect to another page after LOGOUT and i stumbled across this one.

**Comment by Kmaschta** [comment]
The action creator `userLogout` works fine, it is you usage of connect that doesn't work:

In the CodeSandbox above, you are connecting this way:

```js
export default connect(
  undefined,
  { userLogout: userLogout() }
)(MyLogoutButton);
```

But the correct usage is to pass the action creator as is, without calling it:

```js
export default connect(
  undefined,
  { userLogout }
)(MyLogoutButton);
```

With this code, your logout button will works.

**Comment by Kmaschta** [comment]
#3034 should fix the issue. Thanks for reporting it!

**Comment by vaiulian** [comment]
Thank @Kmaschta 

But this doesn't fully resolves the problem with redirect after logout.

like this https://marmelab.com/react-admin/Authentication.html#redirect-after-logout

**Comment by Kmaschta** [comment]
Good catch!

**Comment by shivshankar3578** [comment]
still getting the error 
> TypeError: Cannot read property 'list' of undefined
in the sandbox https://codesandbox.io/s/k9714xnr5v. 
I'm also looking at the same kind of implementation 
Help me, please

**Comment by Kmaschta** [comment]
I don't have any error on your CodeSandbox.
Are you sure this is related to this issue?

**Comment by MonikaMalolepsza** [comment]
Any ideas on how to fix the DropDown Menu positioning? :(

![2019-09-25 15_46_41-simple demo - CodeSandbox](https://user-images.githubusercontent.com/45097166/65606779-c0e2c700-dfab-11e9-9830-f275471620ff.png)

**Comment by djhi** [comment]
Please ask questions on StackOverflow as explained in the issue template and contributing guide
