### ISSUE TITLE
Editing a record throws Total from response is not a number error

### ISSUE THREAD

**Issue by josephktcheung** [marmelab/react-admin#4337]
**What you were expecting:**

Expect it won't log any error in console when changing filter on a `ReferenceManyField`
**What happened instead:**

`Total from response is not a number` error is shown in console when filter prop is changed on `ReferenceManyField` 
**Steps to reproduce:**

1. Go to codesandbox https://codesandbox.io/s/elastic-surf-urpjz
2. Edit a post -> go to comments tab
3. I added a body filter to filter comments in the comments tab in `PostEdit.js`. Change the body filter by typing some characters
4. `Total from response is not a number. Please check your dataProvider or the API` error is thrown in console

![Screenshot 2020-01-22 at 1 25 38 PM](https://user-images.githubusercontent.com/4270232/72867705-c8786980-3d1a-11ea-830b-f5f5e01807fe.png)

**Related code:**

https://codesandbox.io/s/elastic-surf-urpjz

**Other information:**

This is the line which throws the error https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useQueryWithStore.ts#L121. 

I wonder if the check here https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useQueryWithStore.ts#L119-L120 is suitable for `useGetManyReference` / `ReferenceManyField`.

When the filter prop is changed, `useGetManyReference` will use a new [`relatedTo`](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useGetManyReference.ts#L80-L81)  to select ids & total from store, but we are comparing them against the old `relatedTo` (generated using old filter prop)'s ids & total.

**Environment**

* React-admin version: Latest
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):
```
Total from response is not a number. Please check your dataProvider or the API. 
    in Anonymous (at PostEdit.js:151)
    in PostEdit (created by WithPermissions)
    in WithPermissions (created by Router.Consumer)
    in Router.Consumer (created by Route)
    in Route (created by ResourceRoutes)
    in ResourceRoutes (created by Resource)
    in Resource (at src/​index.js:40)
```

**Comment by djhi** [comment]
Thanks for the bug report and the sandbox. Reproduced

**Comment by nacimgoura** [comment]
Same error when I edit one element

**Comment by wmwart** [comment]
the same when updating with a redirect to the list view.
in ra-core version 3.2.4 everything was fine.

**Comment by meastp** [comment]
Same error using `DeleteButton` and `BulkDeleteButton`. Also, I get this error afterwards: `TypeError: record is undefined` - with deletemany there shouldn't be a single record. Also, a valid response from delete and deleteMany (according to the docs) is null.

**Comment by JulienMattiussi** [comment]
I tried to reproduce with your sandBox but unsuccessfully.

(I also forked it to avoid a deprecation message and to have a displayed filter comments more clear for me, but besides that, it's the same)
https://codesandbox.io/s/loving-pascal-pfsge

I also tried some Delete and BulkDelete on it. But I can't see the described error.

Maybe this have been already fixed with later versions ?
Or just the sandbox have changed and don't represent this issue anymore ?
Any advice to reproduce it ?

**Comment by josephktcheung** [comment]
@JulienMattiussi I think it's fixed by these lines https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/dataProvider/useQueryWithStore.ts#L121-L130 which is released in 3.3.0

**Comment by josephktcheung** [comment]
I'm closing this issue. Can anyone try upgrading to 3.3.0 and see if it's fixed for your project? Thanks

**Comment by nacimgoura** [comment]
I use with react-admin 3.3.0 and I still have that error.

**Comment by josephktcheung** [comment]
@nacimgoura can you reproduce it in another codesandbox for your use case?

**Comment by josephktcheung** [comment]
Okay I have reproduced it. v3.3.0 solved the `ReferenceManyField` issue but the same error appears again after I update a post. Attached gif:

![ezgif-7-f86b878b8525](https://user-images.githubusercontent.com/4270232/76629567-7238e180-6579-11ea-8a84-b7df853a1feb.gif)

**Comment by nacimgoura** [comment]
Thanks you @josephktcheung

**Comment by gradasso** [comment]
Same error using BulkDeleteButton and redirect to a list view

**Comment by poerwiyanto** [comment]
Hi, I am still learning to use react-admin. I got the same error after I deleted or edited a record. It also happened when I try to update a record in React-Admin tutorial (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/tutorial). Is there any solution for this issue? Thanks.

**Comment by JulienMattiussi** [comment]
The bug was introduced in 3.3.0
It's happens only if `undoable={true]`
We're working on it

**Comment by tarcisiobruni** [comment]
Same error here. Thanks @JulienMattiussi

**Comment by bateview** [comment]
The error is introduced even when you are deleting an object.

**Comment by fzaninotto** [comment]
But it's fixed in 3.3.3, right?

**Comment by dhstack** [comment]
It is fixed for me in 3.3.3.

**Comment by maier-stefan** [comment]
3.3.3 does not fix it for me....

**Comment by fzaninotto** [comment]
@maier-stefan Can you please post a CodeSandbox showing the error in 3.3.3?

**Comment by maier-stefan** [comment]
OK i got it now running.
I think it was mostly because of my backend (migrated from 2.x.x to 3.3.3)
But still have an issue, ideal i want to use the "simpleRestProvider" as before. but it does not work and still get the total count error, even i return the headers. But with the jsonServerProvider it works.
What could be the issue here?

`import { fetchUtils } from "ra-core";
//import simpleRestProvider from "ra-data-simple-rest";
import jsonServerProvider from "ra-data-json-server";
import { config } from "./config";

const httpClient = (url, options = {}) => {
  if (!options.headers) {
    options.headers = new Headers({
      Accept: "application/json"
    });
  }
  const token = localStorage.getItem("token");
  options.headers.set("Authorization", `Bearer ${token}`);
  return fetchUtils.fetchJson(url, options);
};

export default jsonServerProvider(config.apiBaseUrl, httpClient);
`

**Comment by fzaninotto** [comment]
@maier-stefan For troubleshooting, please use StackOverflow. This bug tracker is for bugs only.
