### ISSUE TITLE
Error in useGetManyAggregate

### ISSUE THREAD

**Issue by KDederichs** [marmelab/react-admin#8684]
**What you were expecting:**
Using the Api Platform Admin (https://github.com/api-platform/admin) I get an error after successfully updating a record.

**What happened instead:**
```
Uncaught TypeError: data is undefined
    onSuccess useGetManyAggregate.js:130
    batchCalls notifyManager.js:62
    notifyFn notifyManager.js:10
    flush notifyManager.js:77
    flush notifyManager.js:76
    batchedUpdates$1 React
    flush notifyManager.js:75
    promise callback*scheduleMicrotask utils.js:322
    flush notifyManager.js:74
    batch notifyManager.js:30
    setQueriesData queryClient.js:89
    updateCache useUpdate.js:168
    update useUpdate.js:314
    step useUpdate.js:43
    verb useUpdate.js:24
    fulfilled useUpdate.js:15
    promise callback*step useUpdate.js:17
    __awaiter useUpdate.js:18
    __awaiter useUpdate.js:14
    update useUpdate.js:252
    useEvent useEvent.js:23
    getMutateWithMiddlewares useMutationMiddlewares.js:90
    save useEditController.js:140
    promise callback*useEditController/save< useEditController.js:138
    handleSubmit useAugmentedForm.js:151
    step useAugmentedForm.js:32
    verb useAugmentedForm.js:13
    __awaiter useAugmentedForm.js:7
    __awaiter useAugmentedForm.js:3
    handleSubmit useAugmentedForm.js:136
    handleSubmit index.esm.mjs:2003
    formHandleSubmit useAugmentedForm.js:167
    React 23
    renderReactElement index.js:337
    doRender index.js:488
    _render index.js:506
```

**Related code:**
https://github.com/marmelab/react-admin/blob/91ca34fc6839c7a3d12670ecd2a4da8487d35ea6/packages/ra-core/src/dataProvider/useGetManyAggregate.ts#L122

adding 

```
            if (!data) {
                return;
            }
```

there seems to fix it.

**Environment**

* React-admin version: 4.8.1
* React version: 18.2
* Browser: Firefox

**Comment by fzaninotto** [comment]
Thanks for your report. 

This seems to be an error in the data provider you're using. As we're not maintaining the API platform data provider, I'll close this issue and I invite you to open it on their repository.

**Comment by KDederichs** [comment]
@fzaninotto 
After digging a bit deeper it seems the issue isn't the api platform provider but an empty `ReferenceInput` in the Edit form.
I do have an optional field that's a relation and the error always appears if you send the edit form with that ReferenceInput being empty. (Error doesn't happen when there's a value).

ReactQuery Dev Tools also has this `["users","getMany",{"ids":["undefined"]}]` which seems to be related.

You think it's an api platform issue still? Seems to be it's react admin related.

**Comment by fzaninotto** [comment]
This looks like an error that has been fixed recently. Can you build a reproduction based on the Simple example CodeSandbox, which uses a local data provider?

**Comment by KDederichs** [comment]
It doesn't seem to do it there (though there's a `["posts","getMany",{"ids":["null"]}]` which is similar). Can you maybe point me to the commit that fixed the error?
Maybe I can poke around a bit to see why it's still happening on my end

**Comment by fzaninotto** [comment]
I think it was released in v4.7.2, see https://github.com/marmelab/react-admin/releases/tag/v4.7.2

**Comment by KDederichs** [comment]
Hmm not seeing anything wrong with it BUT:

Logging the params and options it seems that `options.enabled` in `useGetManyAggregate` is set to false, by my understanding that should disable this call anyways no? Why's `onSuccess` called in the first place then? Cause if it's disabled it would make sense that `data` is undefined cause it's not actually querying.

Forcing it to be enabled fixes the error btw.

**Comment by KDederichs** [comment]
Ok turns out it's expected React-Query behavior: https://tanstack.com/query/v3/docs/react/reference/useQuery:
```
success if the query has received a response with no errors and is ready to display its data. The corresponding data property on the query is the data received from the successful fetch or if the query's enabled property is set to false and has not been fetched yet data is the first initialData supplied to the query on initialization.
```

since it's not enabled and `initialData` is not set and therefore `undefined` that's what's returned there messing it up.

So I guess I'll make a PR setting said `initialData`

**Comment by KDederichs** [comment]
Can't figure it out....
Made a reproducer though, but it's based on a docker image:

To reproduce the error do the following:

1) Execute this reproducer (docker compose up -d): https://github.com/KDederichs/demo/tree/reproducer/update_error
2) Go to the reviews admin
3) Edit any of them, doesn't matter
4) Change something, but leave the selfRef field empty.
5) Click Save
6) See Error

If someone has an idea :)

**Comment by KDederichs** [comment]
Ok I think this time I found it (tm):

After stepping through with the debugger it seems to come from here: https://github.com/marmelab/react-admin/blob/88c777c033cacbeb086983cce83392849e43eadc/packages/ra-core/src/dataProvider/useUpdate.ts#L139

The coll is undefined and it's using that in the `onSuccess` of `useGetManyAggregate`.

Now the fun thing is:
If you set a breakpoint before and step through it coll is actually `[]` which leads me to believe there's actually a race condition there somewhere, maybe react-query not setting the initial cache fast enough or something

**Comment by slax57** [comment]
@KDederichs thanks for the investigation you have done so far.
I tried the provided reproducer (although usually we only accept reproduction cases based on the codesandbox example) with the suggested scenario.

I indeed ran into an error, but not exactly the same as you mention in your original message.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at onSuccess (useGetManyAggregate.js?d6f3:119:1)
    at eval (notifyManager.js?eb8e:62:1)
    at NotifyManager.notifyFn (notifyManager.js?eb8e:10:1)
    at eval (notifyManager.js?eb8e:77:1)
    at Array.forEach (<anonymous>)
    at eval (notifyManager.js?eb8e:76:1)
    at NotifyManager.batchedUpdates$1 [as batchNotifyFn] (react-dom.development.js?03cb:26140:1)
    at eval (notifyManager.js?eb8e:75:1)
```

Is this the error I'm supposed to get?

Besides, I had a look at the PR you opened (thanks for that btw!), but I don't understand why you chose to make the fix in `useUpdate.ts`.
If the stacktrace is correct, to me the fix should rather take place in `useGetManyAggregate.ts`: the `onSuccess` side effect should not throw if `data` is `undefined`.

This error can be reproduced in the simple example btw, so I'll open a PR to fix that in any case.

Can you simply confirm if this is the same error you've got or not?
Thanks.

**Comment by KDederichs** [comment]
Yeah that's the error.

I got to `useUpdate.ts` by using chrome's debugger and looking at the callstack (and stepping through it).

Using the debugger I actually ended up in `useUpdate.ts` where it's updating the cache as the trigger for this.

**Comment by KDederichs** [comment]
Yup, as long as it's fixed I don't really care how :)
